language: cpp
sudo: required

dist: xenial
osx_image: xcode8

os:
  - linux
  - osx

env:
  - ARCH="i386"
  - ARCH="x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Updating Homebrew...";
      brew update;
      brew tap homebrew/versions;
      sudo chown -R $(whoami) /usr/local;
      brew unlink node; brew unlink mercurial; brew unlink cmake; brew unlink autoconf;
      brew install node yasm mercurial cmake gawk ccache autoconf@2.13;
      brew link --overwrite cmake;
      brew link --overwrite mercurial;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -;
      sudo apt-get install nodejs yasm autoconf2.13;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "x86_64" ]]; then
      sudo apt-get update;
      sudo apt-get install libgtk2.0-dev libgtk-3-dev libgconf2-dev;
      sudo apt-get install libasound2-dev libpulse-dev;
      sudo apt-get install libxt-dev libxext-dev libxcb-shm0-dev libx11-xcb-dev;
      sudo apt-get install mesa-common-dev libgl1-mesa-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "i386" ]]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/;
      
      echo "Fixing dependencies"
      sudo apt-get -f install
      sudo dpkg --configure -a
      sudo apt-get -f install
      
      echo "Installing GTK-2.0...";
      sudo apt-get install libgirepository-1.0-1:i386;
      sudo apt-get install libglib2.0-dev:i386;
      sudo apt-get install gir1.2-glib-2.0:i386;
      sudo apt-get install gir1.2-atk-1.0:i386;
      sudo apt-get install libatk1.0-dev:i386;
      sudo apt-get install libfreetype6-dev:i386;
      sudo apt-get install libfontconfig1-dev:i386;
      sudo apt-get install libcairo2-dev:i386;
      sudo apt-get install gir1.2-gdkpixbuf-2.0:i386;
      sudo apt-get install libgdk-pixbuf2.0-dev:i386;
      sudo apt-get install gir1.2-pango-1.0:i386;
      sudo apt-get install libxft-dev:i386;
      sudo apt-get install libpango1.0-dev:i386;
      sudo apt-get install libgtk2.0-dev:i386;
      
      echo "Installing GTK-3.0...";
      sudo apt-get install libxkbcommon-dev:i386 libgtk-3-dev:i386;
      sudo apt-get install libfreetype6-dev:i386 libgconf2-dev:i386;
      sudo apt-get install libasound2-dev:i386 libpulse-dev:i386;
      sudo apt-get install libxext-dev:i386 libxcb-shm0-dev:i386 libx11-xcb-dev:i386;
      sudo apt-get autoremove;
      
      echo "Installing gcc and g++ multilib";
      sudo apt-get install gcc-multilib g++-multilib;

      echo "Installing GL libs...";
      sudo apt-get install mesa-common-dev:i386 libgl1-mesa-dev:i386;
    fi 

script:
  - ./build.sh --arch ${ARCH}

before_deploy:
  - mkdir -p "bin/$MOZ_VERSION/$ARCH"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp build/libMoz2D.so "bin/$MOZ_VERSION/$ARCH/"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp build/libMoz2D.dylib "bin/$MOZ_VERSION/$ARCH/"; fi
  - echo "Library should be in bin/$MOZ_VERSION/$ARCH"
  - ( cd bin/$MOZ_VERSION/$ARCH && ls -la )

deploy:
  provider: bintray
  file: "bintray-${MOZ_VERSION}.json"
  user: "syrel"
  key: ${BINTRAY_API_KEY}
